name: 'Run CLAP Validator'
description: 'Runs clap-validator on a plugin'
inputs:
  version:
    description: 'clap-validator version (e.g. 0.3.2)'
    required: false
    default: 0.3.2
  plugin_path:
    description: 'Path to the CLAP plugin you want to validate'
    required: true
runs:
  using: "composite"
  steps:
    - name: TEST
      run: echo "HELLO"
      shell: bash

    - name: Download clap-validator (linux)
      if: runner.os == 'linux'
      run: |
        curl -L https://github.com/free-audio/clap-validator/releases/download/${{ inputs.version }}/clap-validator-${{ inputs.version }}-ubuntu-18.04.tar.gz -o clap-validator.tar.gz
        tar -xvzf clap-validator.tar.gz
      shell: bash

    - name: Download clap-validator (macos)
      if: runner.os == 'macos'
      run: |
        curl -L https://github.com/free-audio/clap-validator/releases/download/${{ inputs.version }}/clap-validator-${{ inputs.version }}-macos-universal.tar.gz -o clap-validator.tar.gz
        tar -xvzf clap-validator.tar.gz
        mv binaries/clap-validator clap-validator
      shell: bash

    - name: Download clap-validator (windows)
      if: runner.os == 'windows'
      run: |
        powershell -Command "[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; Invoke-WebRequest https://github.com/free-audio/clap-validator/releases/download/${{ inputs.version }}/clap-validator-${{ inputs.version }}-windows.zip -OutFile clap-validator.zip"
        powershell -Command "Expand-Archive clap-validator.zip -DestinationPath ."
      shell: bash

    - name: Check Version
      run: ./clap-validator --version
      shell: bash

    - name: Run validation
      run: ./clap-validator validate ${{ inputs.plugin_path }}
      shell: bash
