name: CI

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  run:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, windows-2022, macos-14]
    steps:
      - name: Get latest CMake
        uses: lukka/get-cmake@latest

      - name: Install Ninja
        if: runner.os == 'Windows'
        uses: seanmiddleditch/gha-setup-ninja@master
  
      - name: Add msbuild to PATH
        if: runner.os == 'Windows'
        uses: microsoft/setup-msbuild@v2
  
      - name: Setup MSVC devcmd
        if: runner.os == 'Windows'
        uses: ilammy/msvc-dev-cmd@v1

      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout clap-plugins
        uses: actions/checkout@v4
        with:
          repository: free-audio/clap-plugins
          path: clap-plugins
          submodules: true
    
      - name: Build clap-plugins
        run: |
          cd clap-plugins
          cmake --preset ninja-headless
          cmake --build --preset ninja-headless --target clap-plugins --parallel

      - name: Test 0.3.2
        uses: ./
        with:
          plugin_path: clap-plugins/builds/ninja-headless/plugins/Debug/clap-plugins.clap
        continue-on-error: true

      - name: Test 0.3.1
        uses: ./
        with:
          version: 0.3.1
          plugin_path: clap-plugins/builds/ninja-headless/plugins/Debug/clap-plugins.clap
        continue-on-error: true

      - name: Test 0.3.0
        uses: ./
        with:
          version: 0.3.0
          plugin_path: clap-plugins/builds/ninja-headless/plugins/Debug/clap-plugins.clap
        continue-on-error: true

      - name: Test 0.3.2 (--only-failed)
        uses: ./
        with:
          plugin_path: clap-plugins/builds/ninja-headless/plugins/Debug/clap-plugins.clap
          args: --plugin_id com.github.free-audio.clap.gain --only-failed
        continue-on-error: true

      - name: Test 0.3.2 (--test-filter)
        uses: ./
        with:
          plugin_path: clap-plugins/builds/ninja-headless/plugins/Debug/clap-plugins.clap
          args: --plugin_id com.github.free-audio.clap.gain --invert-filter --test-filter state-reproducibility-flush
